theme: hitchens-theme
plugins:
  - jekyll-relative-links
  - jekyll-paginate
relative_links:
  enabled: true
  collections: true

github_username: LemurPwned

ignore_theme_config: false
show_excerpts: true
layout: post
paginate: 3
paginate_path: "/blog/page:num/"
hide_search: true
title: Lemurs